springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dundie_awards
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:static/
  web:
    resources:
      static-locations: classpath:static/
      cache:
        period: 0
